services:
  postgres:
    container_name: postgres-truckflow
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: TruckFlow
      POSTGRES_USER: truckflow
      POSTGRES_PASSWORD: Nesher#2019
    ports:
      - 5432:5432
    volumes:
      - truck-postgresdb-data:/var/lib/postgresql/data
    networks:
      - truckflow

networks:
  truckflow:
    external: false

volumes:
  truck-postgresdb-data:
    external: true
    name: truck-postgresdb-data